# Generated by Django 5.1.1 on 2024-09-17 13:10

import django.db.models.deletion
from django.db import models, migrations


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='identifier')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('gender', models.CharField(max_length=1)),
                ('full_name', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('matriculation_number', models.CharField(max_length=20, unique=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.admin')),
            ],
        ),
        migrations.CreateModel(
            name='VoterUpload',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='identifier')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_records', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_records', models.IntegerField(blank=True, null=True)),
                ('file', models.FileField(upload_to='voters')),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('pending', 'Pending'),
                            ('processing', 'Processing'),
                            ('completed', 'Completed'),
                            ('failed', 'Failed'),
                        ],
                        default='pending',
                        max_length=20,
                    ),
                ),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.admin')),
            ],
        ),
    ]
