# fly.toml app configuration file generated for dwst-task-backend on 2024-09-17T20:04:20+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'dwst-task-backend'
primary_region = 'lhr'
console_command = 'uv run manage.py shell'

[build]

[deploy]
  release_command = 'uv run manage.py migrate --noinput'

[env]
  PORT = '8000'

[processes]
app = ""
worker = "uv run manage.py run_huey"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/code/static'
  url_prefix = '/static/'

[mounts]
  source = "dwst_vol"
  destination = "/app/mediafiles"
