# Generated by Django 5.1.1 on 2024-09-17 14:20

import django.core.validators
from django.db import models, migrations


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0002_voter_voterupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='voterupload',
            name='reason',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='voterupload',
            name='file',
            field=models.FileField(
                upload_to='voters',
                validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv', 'xls', 'xlsx'])],
            ),
        ),
    ]
